//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychastniki
    {
        public int ID { get; set; }
        public string Pochta { get; set; }
        public System.DateTime DataRoshdeniya { get; set; }
        public int Ctrana { get; set; }
        public string Telephon { get; set; }
        public string Parol { get; set; }
        public byte[] Photo { get; set; }
        public string Pol { get; set; }
    }
}
